Refactor cert gen, add more debug message and unit tests
DefangLabs/defang pull request #401
Opened 2024-05-21 23:09 UTC by edwardrf

2024-05-21 23:10 UTC, edwardrf commented
ref #400

2024-05-22 17:02 UTC, lionello requested changes

2024-05-22 17:02 UTC, lionello commented on src/pkg/cli/cert.go
> +				term.Infof(" * Please setup CNAME record for %v", domain)
"CNAME or ALIAS"

2024-05-22 17:02 UTC, lionello commented on src/pkg/cli/cert.go
> +func sameIPs(a, b []net.IP) bool {
test

2024-05-22 17:02 UTC, lionello commented on src/pkg/cli/cert.go
> +	if strings.EqualFold(cname, expectedCNAME) {
allow more than 1 CNAME. In particular, allow public FQDN with and without --port

2024-05-23 23:00 UTC, lionello commented on src/pkg/cli/cert.go
> +				sleep(ctx, 5*time.Second) // slight delay to ensure DNS to propagate
we have this in utils/pkg

2024-05-23 23:07 UTC, lionello approved these changes

2024-05-23 23:19 UTC, merged