Fix: Reservations warning should mention defaults (Issue #447)
DefangLabs/defang pull request #589
Opened 2024-07-30 08:14 UTC by shubhrad1

Edited the warning message to specify that provider specific defaults are being used.

2024-07-31 19:47 UTC, lionello commented
Fixes #447

2024-07-31 19:49 UTC, lionello requested changes

2024-07-31 19:49 UTC, lionello commented on src/pkg/cli/compose/validation.go
> +			term.Warnf("service %q: missing memory reservation; using provider-specific defaults. specify deploy.resources.reservations.memory to avoid out-of-memory errors", svccfg.Name)
Looks good! Please capitalize the next word `specify` -> `Specify`

2024-08-01 04:13 UTC, shubhrad1 commented
@lionello I have fixed the typo

2024-08-01 04:56 UTC, lionello approved these changes

2024-08-10 18:33 UTC, merged