Track nodejs download and remove old winget pkg file
DefangLabs/defang pull request #636
Opened 2024-08-23 22:40 UTC by edwardrf

2024-08-24 00:19 UTC, lionello requested changes

2024-08-24 00:19 UTC, lionello commented on pkgs/npm/src/clilib.ts
> +  const downloadUrl = `https://s.dayifu.net/${archiveFilename}?x-defang-source=npm`;
s.defang.io :D

2024-08-25 17:59 UTC, lionello commented
What about this
https://github.com/DefangLabs/defang/blob/main/.github/workflows/go.yml#L315-L326

2024-08-25 18:00 UTC, lionello requested changes
What about this
https://github.com/DefangLabs/defang/blob/main/.github/workflows/go.yml#L315-L326

2024-09-03 19:05 UTC, edwardrf commented
> What about this https://github.com/DefangLabs/defang/blob/main/.github/workflows/go.yml#L315-L326

This update is no longer needed for s.defang.io as it accepts [short URL to latest translation directly](https://github.com/DefangLabs/s.defang.io/blob/main/handler.go#L70-L86).
The update request is kept for now in case we have any need of reverting it back to short.to.

2024-09-04 23:06 UTC, merged