GCP config functions and tail logs for cd, build, and service
DefangLabs/defang pull request #934
Opened 2024-12-19 17:45 UTC by edwardrf

## Description

## Linked Issues

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have added appropriate tests
- [ ] I have updated the Defang CLI docs and/or README to reflect my changes, if necessary

2025-01-25 00:42 UTC, nullfunc commented on src/pkg/cli/client/byoc/gcp/byoc.go
> +				return nil, annotateGcpError(err)
when should annotateGcpError be used? Seems there are some functions which emit both gcp and non-gcp errors but annotateGcpError isn't called for them.

2025-02-01 00:19 UTC, nullfunc commented on src/pkg/cli/client/byoc/gcp/byoc.go
> +		if stat, ok := status.FromError(err); ok && stat.Code() == codes.AlreadyExists {
Can you not overwrite existing secrets?

2025-02-01 00:30 UTC, nullfunc commented on src/pkg/cli/client/byoc/gcp/stream.go
> +				return nil, nil
seems a little weird to return nil, nil as it doesn't allow the caller to decide if it needs to handle data or an error.

2025-02-08 00:38 UTC, lionello commented on src/cmd/cli/command/commands.go
> +			Client:   client,
I'd leave `Client` out of the structure since it's not optional

2025-02-08 00:38 UTC, lionello commented on src/cmd/cli/command/commands.go
> +			Client:   client,
What happened to `args` from the original call?

2025-02-08 00:38 UTC, lionello commented on src/cmd/cli/command/compose.go
> +				return cli.InteractiveDebugForLoadError(ctx, debugConfig)
I had separated the two debug calls so we know what fields are needed in each case, but now they use the same structure and that info is lost?

2025-02-08 00:38 UTC, lionello commented on src/pkg/clouds/gcp/project.go
>  	resourcepb "cloud.google.com/go/resourcemanager/apiv3/resourcemanagerpb"
I'd revert to `resourcemanagerpb`

2025-02-08 00:38 UTC, lionello commented on src/pkg/clouds/gcp/logging.go
> +	t.tleClient.CloseSend()
no err? If it returns an err, use `errors.Join`

2025-02-08 00:38 UTC, lionello commented on src/pkg/clouds/gcp/logging.go
> +		ResourceNames: []string{"projects/" + gcp.ProjectId},
Can `ProjectId` have funky chars or always a number? Does it need escaping?

2025-02-08 00:38 UTC, lionello commented on src/pkg/clouds/gcp/iam.go
>  	iamv1 "cloud.google.com/go/iam/apiv1/iampb"
I'd stick to `iampb` if possible

2025-02-08 00:38 UTC, lionello commented on src/pkg/cli/client/byoc/gcp/stream.go
> +func NewSubscribeStream(ctx context.Context, gcp *gcp.Gcp, reportCD bool) (*SubscribeStream, error) {
create `type ReportCD bool` with two consts true/false resp.

2025-02-08 00:38 UTC, lionello commented on src/pkg/cli/client/byoc/gcp/byoc.go
> +	return b.streamLogs(ctx, req)
why this extra level of indirection if the func sig is the same?

2025-02-08 01:45 UTC, nullfunc commented on src/pkg/cli/client/byoc/gcp/stream.go
> +func (s *ServerStream[T]) Start(start time.Time) {
start is not used.

2025-02-08 02:08 UTC, nullfunc commented on src/pkg/cli/client/byoc/gcp/stream.go
> +		if err := s.tailer.Start(s.ctx, query); err != nil {
What is the expected behavior when user gives an etag for tail? Once the etag logs are show should it stop or start showing all logs since the etag?

2025-02-10 20:53 UTC, edwardrf commented on src/pkg/cli/client/byoc/gcp/byoc.go
> +				return nil, annotateGcpError(err)
The annotateGcpError function was created to abbreviate the gcp error message originally, as the default error output repeats itself and is quite long and confusing. I think we should add it to places where GCP may return errors.

2025-02-10 20:57 UTC, edwardrf commented on src/pkg/cli/client/byoc/gcp/stream.go
> +				return nil, nil
It think it has been the convention for us to ignore messages that subscribe call does not need to handle: https://github.com/DefangLabs/defang/blob/main/src/pkg/cli/subscribe.go#L55-L57

2025-02-11 00:02 UTC, edwardrf commented on src/pkg/cli/client/byoc/gcp/stream.go
> +		if err := s.tailer.Start(s.ctx, query); err != nil {
I think the tail command expectation would be keep tailing until stopped

2025-02-11 00:17 UTC, edwardrf commented on src/pkg/cli/client/byoc/gcp/stream.go
> +func (s *ServerStream[T]) Start(start time.Time) {
fixed

2025-02-11 00:38 UTC, nullfunc commented on src/cmd/cli/command/compose.go
> +				return cli.InteractiveDebugForLoadError(ctx, debugConfig)
I had incorporated in to the config structure but I can see how that might make it harder to see the difference between the calls. I'll talke the loadError out of the config struct and pass it separately.

2025-02-11 18:13 UTC, lionello requested changes

2025-02-11 18:13 UTC, lionello commented on src/pkg/cli/debug.go
> +		Etag:    debugConfig.Etag,
Why remove `Services`?

2025-02-11 18:13 UTC, lionello commented on src/pkg/clouds/gcp/api.go
> +	// listReq := service.Services.List(projectName).Filter("state:ENABLED")
needed?

2025-02-11 18:13 UTC, lionello commented on src/pkg/cli/client/byoc/gcp/byoc.go
> +		logStream.AddJobExecutionLog(execName, startTime)                          // CD log
check `logType` here and only log the build and/or run logs.

2025-02-11 22:00 UTC, nullfunc commented on src/cmd/cli/command/commands.go
> +			Client:   client,
I've put it back as the failedservices

2025-02-11 22:01 UTC, nullfunc commented on src/pkg/cli/debug.go
> +		Etag:    debugConfig.Etag,
fixed

2025-02-11 22:01 UTC, nullfunc commented on src/pkg/cli/debug.go
> +func InteractiveDebugForLoadError(ctx context.Context, debugConfig DebugConfig, loadErr error) error {
fixed

2025-02-12 00:16 UTC, lionello commented on src/pkg/cli/debug.go
> +	return interactiveDebug(ctx, client, DebugConfig{}, loadErr)
```suggestion
	return interactiveDebug(ctx, client, DebugConfig{Project: project}, loadErr)
```

2025-02-13 00:41 UTC, nullfunc approved these changes

2025-02-13 00:43 UTC, merged